
services:
  app:
    image: chat-generator:latest
    networks:
      - traefik_proxy

    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chat_generator.entrypoints=websecure"
        - "traefik.http.routers.chat_generator.rule=Host(`${APP_DOMAIN?domain is necessary}`)"
        - "traefik.http.routers.chat_generator.tls=true"
        # - "traefik.http.routers.chat_generator.tls.certresolver=cf"
        - "traefik.http.services.chat_generator.loadbalancer.server.port=3000"

networks:
  traefik_proxy:
    external: true
